const data = [
  {
    id: 1,
    first_name: "Ring",
    last_name: "Beaconsall",
    email: "rbeaconsall0@goo.gl",
    gender: "Male",
  },
  {
    id: 2,
    first_name: "Hoebart",
    last_name: "Huxtable",
    email: "hhuxtable1@china.com.cn",
    gender: "Male",
  },
  {
    id: 3,
    first_name: "Verne",
    last_name: "Alyonov",
    email: "valyonov2@newsvine.com",
    gender: "Male",
  },
  {
    id: 4,
    first_name: "Joye",
    last_name: "Britian",
    email: "jbritian3@gov.uk",
    gender: "Female",
  },
  {
    id: 5,
    first_name: "Kippar",
    last_name: "Samworth",
    email: "ksamworth4@indiegogo.com",
    gender: "Male",
  },
  {
    id: 6,
    first_name: "Bastien",
    last_name: "Grelik",
    email: "bgrelik5@edublogs.org",
    gender: "Male",
  },
  {
    id: 7,
    first_name: "Devonna",
    last_name: "Darree",
    email: "ddarree6@ifeng.com",
    gender: "Female",
  },
  {
    id: 8,
    first_name: "Winnie",
    last_name: "Geldart",
    email: "wgeldart7@stanford.edu",
    gender: "Male",
  },
  {
    id: 9,
    first_name: "Christine",
    last_name: "Warry",
    email: "cwarry8@cloudflare.com",
    gender: "Female",
  },
  {
    id: 10,
    first_name: "Emmett",
    last_name: "Coste",
    email: "ecoste9@nationalgeographic.com",
    gender: "Male",
  },
  {
    id: 11,
    first_name: "Priscilla",
    last_name: "Bonnell",
    email: "pbonnella@devhub.com",
    gender: "Female",
  },
  {
    id: 12,
    first_name: "Emilie",
    last_name: "Vigers",
    email: "evigersb@yahoo.com",
    gender: "Female",
  },
  {
    id: 13,
    first_name: "Franz",
    last_name: "Tombleson",
    email: "ftomblesonc@about.com",
    gender: "Male",
  },
  {
    id: 14,
    first_name: "Cesya",
    last_name: "Lilian",
    email: "cliliand@etsy.com",
    gender: "Female",
  },
  {
    id: 15,
    first_name: "Lisbeth",
    last_name: "Pyne",
    email: "lpynee@google.de",
    gender: "Female",
  },
  {
    id: 16,
    first_name: "Florette",
    last_name: "O'Dyvoy",
    email: "fodyvoyf@elegantthemes.com",
    gender: "Genderqueer",
  },
  {
    id: 17,
    first_name: "Thorny",
    last_name: "Raimbauld",
    email: "traimbauldg@example.com",
    gender: "Male",
  },
  {
    id: 18,
    first_name: "Sharl",
    last_name: "Gecks",
    email: "sgecksh@baidu.com",
    gender: "Bigender",
  },
  {
    id: 19,
    first_name: "Arel",
    last_name: "Dewey",
    email: "adeweyi@webnode.com",
    gender: "Male",
  },


];

export default data